project:
  type: website
  output-dir: docs
resources: CNAME
bibliography: references.bib
mainfont: Atkinson Hyperlegible
logo: images/rmmonkey.png
website:
  title: Intermediate Research Methods 
  repo-url: https://github.com/LittleMonkeyLab/interrm
  site-url: http://interrm.littlemonkeylab.com/
  repo-actions: issue
  navbar:
    left:
    - text: "Coursework Information"
      menu:
      - coursework/coursework.qmd
      - coursework/courseworkCP.qmd
      - coursework/courseworkMD.qmd
      - coursework/courseworkCHIP.qmd
    # right:
    # - text: Schedule
    #   href: schedule.qmd
    # - text: Coursework Info
    #   href: coursework.qmd
    # - text: Staff
    #   menu:
    #   - text: Dr. Gordon Wright
    #     href: https://littlemonkeylab.github.io/
    # - icon: github
    #   href: https://github.com/
    #   aria-label: GitHub
  sidebar:
    logo: "images/rmmonkey.png"
    style: docked
    alignment: left
    border: true
    collapse-level: 1
    contents:
    - section: Overview
      contents:
      - text: Syllabus
        href: index.qmd
    - section: Content
      contents: auto

  page-footer:
    center: Copyright 2024, Dr. Gordon Wright
execute:
  freeze: auto
  self-contained: true
  
format:
  html:
    code-overflow: wrap
    engine: knitr
    code-line-numbers: false
    code-copy: hover
    theme:
      light: light.scss
      dark: dark.scss
    mainfont: Atkinson Hyperlegible
    monofont: Fira Code
    toc: true
    link-external-newwindow: false
    link-external-icon: false
    css: include/webex.css
    include-after-body: include/webex.js
comments:
  hypothesis:
    openSidebar: false
    showHighlights: whenSidebarOpen
    focus:
      user:
        username: drdeception
filters:
  - panelize
  - webr