---
title: Critical Proposal
author: Dr. Gordon Wright
categories: coursework
---

# Detailed Critical Proposal Briefing

# Critical Proposal Coursework Brief 23-24

Write an 1,800 word critical evaluation on an empirical paper from a
Psychology Journal within your chosen field of research, including
critical reflection of how you and your group might improve upon it,
and/or build on its strengths.

-   70% of your mark will depend on the quality of your critical
    assessment
-   30% will depend on your suggestions for how your individual and
    group efforts in the Mini-Dissertation might improve research in
    this area. (See Rubric for more detail.)

**Important notes**: - We stop marking at 1,800 words. No penalty for
going over, but the words you use after 1,800 words cannot win you
marks. - Worth 15% of your module grade for PS52007D (30 Credits). -
Your reference list does not count towards the word count. - You must
use the Critical Proposal Coversheet and use ONLY your 8-digit Student
ID in the filename. - You must focus on an empirical article (i.e. an
article that reports the collection of quantitative data) from a
Psychology Journal. You are encouraged to confirm the suitability of
your paper with your Lab Tutor. - You MUST provide a full APA reference
to your chosen paper at the top of your essay. - You MUST include a copy
of the Experimental Design Schematic with information on at least one IV
(name and factor levels) and an effect size developed from the paper
(see week 3 lab materials). - Although lab groups are collaborative,
this must be your individual work, and collusion or plagiarism may
result in a penalty or misconduct review. - An AI declaration
(regardless of whether you used AI or not) is compulsory.

### Learning outcomes:

-   To encourage a deeper and more rigorous approach to reading
    published research.
-   Appraise the process of psychological research and assess the merits
    of particular studies.
-   Assess the reporting of research in published sources.
-   Critically reflect on how research practices may be improved, or
    strengths built upon, and the possible value of research increased
    in your forthcoming Mini-Dissertation.

Your work should be in an essay format with an introduction and critical
reflection/conclusion. It should not have sub-headings within the text,
but you are recommended to cover all of the general areas presented
below, with a focus on the most important aspects.

**The deadline for handing in your Critical Proposal is: Friday, 1st
November 2024, before midday.**

------------------------------------------------------------------------

## Suggested Outline

### Summary (Compulsory and Important)

Provide a summary of the article in 150-200 words in which you capture
the essentials of the Target Paper.

```         
(a) What is the research domain and core question of the paper and what is of interest to you?

(b) What is the method that you are focussing on?

(c) What are the relevant results?

(d) Were there significant flaws or limitations in the study that might give you insight into your own research ahead?
```

### Research Question

Do the authors link their experiment to wider issues and theories in
psychology? What question is the paper trying to answer? Is the
hypothesis clear? Is it well-argued?

### Method

Is it clear and unambiguous? Could another (better) method have been
used? Could you carry out a replication from this report? Is the design
the most efficient for the purpose? Have broad theoretical constructs
been well operationalized into specific variables?

### Outcome

Is the Results section clear? Is the analysis unambiguous? Are all
analyses and statistical choices appropriate? Did the experimenter
answer the question?

### Experimental Design Schematic

You are required to complete details of one IV and an effect size (drawn
from the target paper) at least!

### Discussion

Are the inferences from the results justified? Well-argued? Do they
advance our knowledge? What further questions are raised by the results?
What experiments might be done to answer them?

### Suggested Improvements

Which aspects of the research project could be improved? Is there a
better research design? Are there extraneous or confounding variables?
How would you remove them? Could the results be more clearly analysed
and presented? Think also about which aspects of the paper itself could
be improved. Were the hypotheses clearly reported and well-justified?
Would you have displayed information differently (e.g., in figures or
graphs)?

### Critical Reflection and Conclusion

-   What were the key strengths and/or weaknesses of the paper? Did you
    find the paper clear? Do you think it provides a persuasive answer
    to the research question set out, or are there important limitations
    that limit its overall usefulness?
-   How will your Mini-Dissertation improve the research presented?
-   Why is it important that YOU do this research? How will you
    implement ‘Best Practice’ in the Mini-Dissertation?
-   What has this exercise taught you, and how has it developed your
    metacognitive abilities?

------------------------------------------------------------------------

### Useful Readings (available online in the library reading list):

-   Bell, P., Staines, P., & Mitchell, J. (2001). *Evaluating, doing and
    writing research in psychology*. London: Sage. (Chapters 5 & 6)
-   Haslam, A., & McGrarty, C. (2014). *Research Methods and Statistics
    in Psychology*. London: Sage. (Checklists on pp. 29-

## Rubric

# CRITICAL PROPOSAL MARKING RUBRIC - 1,800 WORDS (MAX)

| Criteria                                                                                                                                                                                                            | FAIL (UNSATISFACTORY)                                                                                                                                                 | 3RD (SATISFACTORY)                                                                                                                                                                                             | LOWER 2ND (GOOD)                                                                                                                                                                                                                                                | UPPER 2ND (VERY GOOD)                                                                                                                                                                                             | FIRST (EXCELLENT)                                                                                                                                                                                                                                                                            |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **SUMMARY:** \[Does the proposal summarise the chosen empirical article?\]                                                                                                                                          | There is no summary of the chosen empirical paper.                                                                                                                    | The chosen empirical paper is described, but with inaccuracies or imprecision.                                                                                                                                 | The chosen empirical paper is described, with only a few errors, gaps, or a minor lack of clarity.                                                                                                                                                              | The chosen empirical paper is clearly and fully summarised, with appropriate terminology and precision.                                                                                                           | The chosen empirical paper is clearly and fully summarised, with excellent terminology, accuracy and accessibility, showing a comprehensive understanding of the paper.                                                                                                                      |
| **RESEARCH QUESTION:** \[Does the proposal critique the research question and general domain?\]                                                                                                                     | There is no overview of the research domain or research question addressed.                                                                                           | The proposal summarises the research area and general question addressed, but does so imprecisely or with errors.                                                                                              | The proposal accurately summarises the domain of research and the specific question addressed in the paper.                                                                                                                                                     | The proposal accurately summarises the domain of research and the specific question addressed in the paper and does so in an accessible and precise manner.                                                       | The proposal accurately summarises the domain of research and the specific question addressed in the paper and does so in an accessible and precise manner while evaluating the merit or importance of the research.                                                                         |
| **METHOD:** \[Does the proposal critically evaluate the chosen method and operationalisation of variables?\]                                                                                                        | There is no attempt to evaluate the methods of the paper.                                                                                                             | Evaluation of the methods are few and preliminary.                                                                                                                                                             | Evaluation of the method is clear, but doesn't consider important aspects.                                                                                                                                                                                      | Evaluation of the method is clear and focusses on important aspects.                                                                                                                                              | Evaluation of the method is clear, identifies the most important aspects, and the impact on possible results is argued.                                                                                                                                                                      |
| **OUTCOME:** \[Has the proposal critically evaluated the analysis, reporting, and interpretation of the results?\]                                                                                                  | There is no discernible evaluation of the results section.                                                                                                            | The proposal makes few, superficial comments on the presentation and analysis of results.                                                                                                                      | The proposal makes a good attempt at presenting an evaluation of the results, but they are preliminary.                                                                                                                                                         | The proposal makes good suggestions for how the results may be more accurately presented and analysed.                                                                                                            | The proposal shows insight in the evaluation of analysis, reporting and interpretation of the results of the chosen study.                                                                                                                                                                   |
| **DISCUSSION:** \[Does the proposal address how well results are integrated into the literature, and how the authors address limitations and opportunities for extension?\]                                         | The proposal has failed to address how the results sit within the literature or the authors efforts to critique their own work.                                       | The proposal presents preliminary ideas on how the research integrates results and appraises the research.                                                                                                     | The proposal presents clear appraisal of how the research integrates results and appraises the research.                                                                                                                                                        | The proposal presents thoughtful evaluation of how the research integrates results and appraises the research.                                                                                                    | The proposal examines how results are discussed well and presents a robust examination of the researchers discussion.                                                                                                                                                                        |
| **IMPROVEMENTS:** \[Does the proposal present means by which to avoid limitations and/or build on strengths of the study?\]                                                                                         | The proposal makes no effort to mitigate limitations or build on strengths.                                                                                           | The proposal has identified steps by which to EITHER avoid limitations or accentuate positive aspects of the study.                                                                                            | The proposal has dealt with limitations AND strengths and proposed improvements.                                                                                                                                                                                | The proposal has identified important limitations and strengths and presented feasible improvements.                                                                                                              | The proposal identifies and argues the most salient areas of improvement and presents carefully considered and supported suggestions for improvement.                                                                                                                                        |
| **CRITICAL REFLECTION/CONCLUSION:** \[Does the proposal clearly summarise key points from the essay and propose specific means by which the student may improve research in this area?\]                            | There is no reflection on how the points made in the essay work together or how the student may feasibly improve work in this area.                                   | There is an effort to synthesise the argument made during the essay and an attempt to illustrate how the author may improve research in this area, but it is vague.                                            | A conclusion is presented and it features reflections on future improvement that don't tie together or have limited focus on priority.                                                                                                                          | The conclusion brings the main points of the critique together and a clear set of ideas presented by which the student may improve research in the area.                                                          | The conclusion synthesises the main points of the critique nicely with clear evaluation. The student has presented a thoughtful and focussed reflection on how they might make a meaningful improvement in the research field.                                                               |
| **DESIGN SCHEMATIC:** \[The inclusion of a copy of the Experimental Design Schematic 2x2 grid is required. At the very least, it must include details of a single IV, with 2 levels, and a calculated Effect Size\] | Design Schematic not included.                                                                                                                                        | Design Schematic included but fails to either break down one IV with two levels (relevant to the target paper) or present an effect size                                                                       | Presents the schematic with correct details of at least one IV with an effect size                                                                                                                                                                              | The Design Schematic is presented and includes correct information for one IV, an effect size and at least one other element (e.g. Hypothesis, Sample Size, Details of DV)                                        | The Design Schematic is presented and includes correct information for both IVs, an effect size for each and at least two other elements (e.g. Hypotheses, Sample Size, Details of DV)                                                                                                       |
| **FORMAT AND REFERENCING:** \[Is the proposal well-written, well-presented, with appropriate in-text citations and references?\]                                                                                    | The proposal is poorly formatted and referencing is either absent or very poorly inserted / inaccurately listed at the end.                                           | The format is adequate and there is some appropriate referencing, but there are also lots of inaccuracies and omissions.                                                                                       | The format and referencing is appropriate for the most part, but there are a number of minor errors.                                                                                                                                                            | Formatting is good and references are inserted accurately and appropriately in the text and listed correctly at the end.                                                                                          | The format is clear and professional and referencing is to a high academic standard.                                                                                                                                                                                                         |
| **GRADE:** \[Why was your proposal placed within its particular degree class?\]                                                                                                                                     | A typical fail contains no or very limited material to indicate the student has attended relevant lecture(s), attended relevant labs or read any relevant literature. | A typical third class proposal presents material that is for the most part relevant, but it is poorly organised and tends to contain quite a few errors, is overly general, or indicative of misunderstanding. | A typical 2:2 proposal contains relevant material that is mostly accurately presented (although there may be a few minor errors). However, the proposal fails to elaborate or integrate aspects of the critique into a logical structure or coherent narrative. | A typical 2:1 proposal presents relevant material with very few errors. It is well organised and clearly expressed. However, the level of analysis is not particularly deep and critical reflection is formulaic. | A typical first class proposal presents highly relevant wide-ranging material that clearly addresses a considered critique of the study and domain. It also includes specific ideas on how the Mini-Dissertation (and future work by the student) may tangibly improve research in the area. |

**Note:** A DECLARATION OF AI USE (OR NOT) IS COMPULSORY.
