---
title: Coursework for Research Methods PS52007D
author: Dr. Gordon Wright
categories: coursework
---

# Coursework for Research Methods PS52007D 2024/5

Here is information on the coursework.

## Module weight and progression requirements

This is a 30 credit module and you must complete attempts and pass all
three coursework elements (Critical Proposal, Mini-Dissertation and CHIP
Learning Log) in order to pass the module.

The module is anticipated to involve 300 hours of your time. This is a
significant piece of work, and runs parallel to the rest of your
programme. Time and project management is an integral part of this
assessment.

20 hours of lectures 40 hours of labs 240 hours of independent study
(including literature search and review, reading, experimental design
and development, data collection, analysis, interpretation of result and
writing up) If you do not submit (or fail) any element, resubmission is
possible by July 14th 2023.

If you do not pass at this point, resubmission (3rd attempt) would next
be possible in March 2024 - meaning you would be eligible to enter year
3 in October 2024.

## Attendance and Participation

You are expected to attend and participate in your weekly labs and group
work.

At the start of each lab session, you are required to complete the very
short Lab 'Pulses' - brief check-in questionnaires - which will help us
to monitor your well-being, your progress and survey the entire group
for questions relevant to the module and forthcoming teaching.

At the end of each lab, you are given notice of the approaching end of
the session and will be asked to document anything you feel is important
and reflect on the progress made. These 'generative activities' are
modest, extremely so, but will give you important information from which
to develop an understanding of your learning - so called
'metacognition'.

Modest milestones are in place throughout the course to help structure
your efforts. Please listen to your Lab Tutors when they suggest these.
They are not designed to be a burden, but rather to give you the best
chance of success. It is common that you may not take them seriously,
but in due course, it may become apparent that they were a good idea.
The hope is that by having them in place this year, you can advisedly
chose to include them in a project timeline for your Year 3
dissertation.

The coursework mentioned below has strict deadlines, with the normal
RASA accommodations. If you will be using a RASA, please take the time
to discuss it with the Teaching Team (in confidence) as on projects like
your Mini-Dissertation, making use of various support is not something
that happens right at the end of the process.

Applications for Ethical approval (a compulsory step in the process of
your Mini-Dissertation) are not permitted after the end of Term 1, and
can be submitted at any time in Term 1, depending on your readiness.

You are not required to use your OneNote Lab Notebook apart from in a
small number of very specific cases. Two examples are the Experimental
Design page, and the Analysis Plan page. In these, you are asked to
specify the design of your experiment and the analysis type you are
going to use. These are important milestones, and ones that can often
trip you up down the line, and we have learned that by 'getting these
down on paper', you don't second guess yourself, forget, or take a wrong
turn at some point in the future.

## Critical Proposal - 1,800 words (15%) due: 12pm (midday) 1st November 2024 (end of Wk 5)

The first deadline you have is the Critical Proposal.

You are asked to identify a peer-reviewed article from a Psychology
journal which features a behavioural task or psychometric tool/measure
which may be relevant to your research topic. You are asked to
critically evaluate the paper, or a specific part of the paper (e.g. a
single study out of a multi-study paper) and critically reflect on how
you might consider building upon the strengths you outline, or improving
on any weaknesses.

The mark is work 15% of the module grade and 70% of the mark is
allocated towards the critical evaluation, with 30% being allocated
towards the critical reflection and plans to develop your study.

A detailed brief can be found here and a detailed rubric/marking guide
can be found here

Learning outcomes:

To encourage a deeper and more rigorous approach to reading published
research Appraise the process of psychological research and assess the
merits of particular studies Assess the reporting of research in
published sources Critically reflect on how research practices may be
improved, or strengths built upon, and the possible value of research
increased in your forthcoming Mini-Dissertation nb. It is compulsory
that you chose a peer-reviewed article. It must be an article that
reports an empirical study (i.e. they collect and interpret data). It
must be from a domain of psychology, and it must have an element that
can feasible play a part in your study.

It is considered an error on your part to not give yourself time to
consider if the paper you have chosen conforms to these parameters, and
your Lab Tutor is able to assist you very overtly. It is encouraged.
Choosing a good paper is part of the assessment.

## Mini-Dissertation - 2,500 word APA format (lab)report with Open Data, Open Materials and Reflective Account - due 12pm (midday) 28th March 2025 (end of week 20)

Your Mini-Dissertation is absolutely identical in structure and function
to a normal APA lab-report - the type you did 3 of last year. The only
difference is that nothing comes 'ready-made'. To assist you in this
process, you will have your group (3 or 4 student ONLY). You will have
your Teaching Team (MC and LTs) and you will have your Personal Tutors
cheering you on.

The Mini-Dissertation is worth 70% of your module grade.

Over the course of 20 weeks, you will:

Identify an area of psychological research Review and critique the
literature in this area Design a 2x2 ANOVA experiment that is unique to
you but mobilised in your group. Develop a testable hypothesis Obtain
Ethical Approval for your experiment Collect REAL data Analyse these
data Write up the results in APA format report of no more than 2,500
words in length from first word of the Introduction to the last word of
the Discussion Submit supporting materials (Open Data, Open Materials
and a very modest Critical Reflection ± 200 words) A detailed rubric can
be found here

Extensive supporting materials are provided and you will be supported
every step of the way. The only way you can have problems is by not
contributing or attending. You are going to make lots of decisions,
individually and as a group, and some may be ones that you later reflect
on as 'sub-optimal' - fantastic. If you aren't making mistakes, you
aren't doing it right. We do not let anyone impair their marks for
decisions made early in the process. Please have confidence in that.
Jump in!

## CHIP learning log - 2x 600 word Reflective Accounts on different topics with references - Due: 12pm (midday) 11th April 2025 ( weeks after end of term 2)

CHIP stands for Conceptual, Historical and Integrative Perspectives.

During the course of the year, a range of concepts, debates and
questions will be posed and presented in the lectures. Hopefully we will
explore topics that are meaningful and salient to you as a group and as
burgeoning scientists.

Over the course of the year, we want you to consider these concepts,
engage with these debates, or reflect on questions around how Psychology
contributes or conflicts with you as an individual, a future scientist,
or a developing life-long learner.

A detailed rubric can be found here

You are asked to present 2 'reflections' on topics raised during the
year.

To be eligible as a 'topic' this must be proposed and agreed by the
class, but it is as open as that.

The first reflective account requires you to adopt 2 perspectives from
the following list and reflect on any of the topics raised during the
year:

As a STUDENT of psychology As a TRAINEE psychologist In relation to a
RESEARCH application in your future As an HISTORIAN of psychology
Reporting on the culture or PRACTICE of psychology as it currently
exists here or across cultures As a critic or supporter of psychology's
status as a SCIENCE The second reflective account takes a single
identified starting point (a reading, a TED talk, a cartoon or TikTok
video etc) but then logs your journey of exploration into an approved
topic. How has your understanding developed? How did you pursue this
idea? What reactions did you experience to new ideas? What have you
learned or re-discovered during this process of learning?
